# SPDX-License-Identifier: Apache-2.0
"""The RISC-V architectural tests as a Bazel repository.

`act_tests` fetches the `riscv-arch-test` source tree at a pinned
commit. It then reads the configuration header of every test, the YAML
between `START_TEST_CONFIG` and `END_TEST_CONFIG`, and writes it into
`tests.bzl` as a list named `TESTS`. The list lets `//act:defs.bzl`
select the tests that apply to a device in the analysis phase, which
cannot read files.

The ACT4 framework does the same selection in Python, in
`framework/src/act/select_tests.py`. This rule replaces that step, so
the build needs neither Python nor the Ruby tools of the framework.
"""

# The directories that hold the tests, relative to the source tree.
_TEST_DIRS = ["tests/rv32i", "tests/priv"]

def _unquote(s):
    s = s.strip()
    if len(s) >= 2 and s[0] == s[-1] and s[0] in ("'", "\""):
        return s[1:-1]
    return s

def _parse_list(s):
    """Parses a flow list such as `['I', ['Zca', 'C'], 'M']`.

    Returns a list whose items are strings, or lists of strings for a
    nested list, which means that any one of its extensions will do.
    """
    s = s.strip()
    if not (s.startswith("[") and s.endswith("]")):
        fail("not a list: " + s)
    s = s[1:-1]
    out = []
    cur = ""
    depth = 0
    for c in s.elems():
        if c == "[":
            depth += 1
            cur = ""
        elif c == "]":
            depth -= 1
            out.append([_unquote(x) for x in cur.split(",") if x.strip()])
            cur = None
        elif c == "," and depth == 0:
            if cur != None and cur.strip():
                out.append(_unquote(cur))
            cur = ""
        elif cur != None:
            cur += c
        else:
            cur = c if c.strip() and c != "," else ""
    if cur != None and cur.strip():
        out.append(_unquote(cur))
    return out

def _scalar(s):
    s = _unquote(s)
    if s == "true":
        return True
    if s == "false":
        return False
    if s.isdigit():
        return int(s)
    return s

def _parse_header(path, content):
    start = content.find("START_TEST_CONFIG")
    end = content.find("END_TEST_CONFIG")
    if start < 0 or end < 0:
        fail("no test configuration in " + path)
    lines = content[start:end].split("\n")[1:-1]
    meta = {
        "required": [],
        "forbidden": [],
        "march": "",
        "needs_signature": True,
        "min_harts": 1,
        "params": {},
    }
    in_params = False
    for line in lines:
        line = line.lstrip()
        if line.startswith("#"):
            line = line[1:]
        elif line.startswith("//"):
            line = line[2:]
        if not line.strip() or line.strip().startswith("#"):
            continue
        indented = line.startswith("  ")
        key, sep, value = line.strip().partition(":")
        if not sep:
            fail("cannot read line `%s` in %s" % (line, path))
        if in_params and indented:
            meta["params"][key] = _scalar(value)
            continue
        in_params = False
        if key == "REQUIRED_EXTENSIONS":
            meta["required"] = _parse_list(value)
        elif key == "FORBIDDEN_EXTENSIONS":
            meta["forbidden"] = _parse_list(value)
        elif key == "MARCH":
            meta["march"] = value.strip()
        elif key == "NEEDS_SIGNATURE":
            meta["needs_signature"] = _scalar(value)
        elif key == "MIN_HARTS":
            meta["min_harts"] = _scalar(value)
        elif key == "params":
            in_params = True
        else:
            fail("unknown key `%s` in %s" % (key, path))
    return meta

def _act_tests_impl(rctx):
    rctx.download_and_extract(
        url = rctx.attr.url,
        sha256 = rctx.attr.sha256,
        stripPrefix = rctx.attr.strip_prefix,
    )
    tests = []
    for d in _TEST_DIRS:
        for suite in sorted(rctx.path(d).readdir(), key = lambda p: p.basename):
            for f in sorted(suite.readdir(), key = lambda p: p.basename):
                if not f.basename.endswith(".S"):
                    continue
                rel = "%s/%s/%s" % (d, suite.basename, f.basename)
                meta = _parse_header(rel, rctx.read(f))
                meta["src"] = rel
                meta["suite"] = suite.basename
                meta["name"] = f.basename[:-2]
                tests.append(meta)
    rctx.file("tests.bzl", "\n".join([
        "# Generated by //act:repo.bzl from the tests' own headers.",
        "",
        "# The commit of riscv-arch-test the tests come from.",
        "ACT_COMMIT = %r" % rctx.attr.url.split("/")[-1].removesuffix(".tar.gz"),
        "",
        "TESTS = " + json.encode_indent(tests, indent = "    ").replace(
            "true",
            "True",
        ).replace("false", "False"),
        "",
    ]))
    rctx.file("BUILD.bazel", """\
# Generated by //act:repo.bzl.
package(default_visibility = ["//visibility:public"])

exports_files(glob(["tests/**/*.S"]))

# The shared test environment: the macros, the trap handler and the
# signature layout every test includes.
filegroup(
    name = "env",
    srcs = glob(["tests/env/**"]),
)
""")

act_tests = repository_rule(
    implementation = _act_tests_impl,
    doc = "Fetches riscv-arch-test and writes the catalog of its tests.",
    attrs = {
        "url": attr.string(
            mandatory = True,
            doc = "The source archive of riscv-arch-test, at one commit.",
        ),
        "sha256": attr.string(
            mandatory = True,
            doc = "The checksum of that archive.",
        ),
        "strip_prefix": attr.string(
            doc = "The directory inside the archive that holds the tree.",
        ),
    },
)
